### ISSUE TITLE
Felloggning krashar service

### ISSUE THREAD

**Issue by r0stig** [imbox/kanin#1]
Rad:
https://github.com/imbox/kanin/blob/master/index.js#L372

Stacktrace:
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Kanin._reply (/code/node_modules/kanin/index.js:372:64)

Scenario:
Vi får in ett meddelande utan correlationId (råkade använda mq.publish istället för mq.request), när vi sedan kör en reply på det meddelandet så krashar hela servicen. Förvisso handhavandefel men känns lite hårt att ett lib kan orsaka att servicen krashar helt :-) .

**Comment by luddd3** [comment]
Tanken är i alla fall att detta lib bara ska bubbla upp felet med en
beskrivande text, men det misslyckas ju helt på grund av att den inte kunde
serialisera meddelandet. Vi kan använda någon form av "safe stringify"
(t.ex. https://github.com/davidmarkclements/fast-safe-stringify) för att
fixa det.

2018-07-12 14:05 GMT+02:00 Robert Säll <notifications@github.com>:

**Comment by luddd3** [comment]
Fixed by 6f6599b
